[build]
builder = "nixpacks"
buildCommand = "npm install && cd services/api && npm install --include=dev && npm run build"

[deploy]
startCommand = "cd services/api && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "4000"
